version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: movieapp_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: movieapp
    volumes:
      - mongodb_data:/data/db
    networks:
      - movieapp_network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: movieapp_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/movieapp?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here
      TMDB_API_KEY: your_tmdb_api_key_here
      TMDB_BASE_URL: https://api.themoviedb.org/3
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - movieapp_network

  # Frontend React App
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: movieapp_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_TMDB_IMAGE_BASE_URL: https://image.tmdb.org/t/p
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - movieapp_network

volumes:
  mongodb_data:

networks:
  movieapp_network:
    driver: bridge
